### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SoYoung210** [SoYoung210/project-template#1]
# Task
- [ ] input (pj name, author , / TB redux)
- [ ] cli git clone 
- [ ] input 값으로 readme와 package.json 내용 replace
- [ ] yarn add
